post:
    tags:
      - Tasks
    summary: dublicate-tasks
    description: 'dublicate-tasks '
    operationId: dublicate-tasks
    security:
    - bearerAuth: []
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
    - name: request body
      in: body
      schema:
        type: object
        required:
          - task_id
        properties:
          task_id:
            type: integer

      required: true
    responses:
      '200':
        description: successful operation
      '400':
        description: bad request
      '401':
        description: unauthenticated user
      '422':
        description: validation error

