get:
  tags:
    - Tasks
  summary: Get All Tasks of Section
  description: 'Get All Tasks of Section '
  operationId:  List Tasks
  security:
  - bearerAuth: []
  consumes:
    - application/json
  produces:
    - application/json
  parameters:
    - name: id
      in: path
      schema:
        type: integer
        required:
        properties:
  responses:
    '200':
      description: successful operation
    '400':
      description: Bad request
    '401':
      description: unauthenticated user
    '422':
      description: validation error
