post:
    tags:
      - Tasks
    summary: Update Client Tasks
    description: Update Client Tasks
    operationId: update-client-tasks
    security:
    - bearerAuth: []
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
    - name: request body
      in: body
      schema:
        type: object
        required:
          - tasks
        properties:
          tasks:
            type: array
            description: list of client tasks
            items:
              required:
                - id
              properties:
                id:
                  type: integer
                answer:
                  type: string
                file:
                  type: string
                  description: encoded with base64
                file_name:
                  type: string
                  description: required with file
    responses:
      '200':
        description: successful operation
      '400':
        description: Bad request
      '401':
        description: unauthenticated user
      '422':
        description: validation error
